(function () {
    'use strict';

    /**
     * Exposes worker functions.
     *
     * @param functions - Map of name to function
     * @param readyPromise - A promise that must be resolved before any worker function calls
     */
    function expose(functions, readyPromise) {
        self.onmessage = async (msg) => {
            await readyPromise;
            const { name, args, transferableIndices } = msg.data;
            const transferables = [];
            let data;
            try {
                const workerFunction = functions[name];
                if (typeof workerFunction !== 'function') {
                    console.error(`${name} is not an exposed worker function`);
                    self.close();
                    return; // close doesn't immediately kill the worker
                }
                const result = await workerFunction(...args);
                args.forEach((arg, i) => transferableIndices.includes(i) && transferables.push(arg));
                data = { type: 'success', result, transferables };
            }
            catch (error) {
                const { message, name } = error;
                data = {
                    type: 'error',
                    error: {
                        message,
                        name
                    }
                };
            }
            self.postMessage(data, transferables);
        };
    }
    /**
     * Loads wasm generated by emscripten.
     *
     * @param script - The name of js wrapper.
     * @param options - The URL prefix of files if use CDN and function to execute before promise resolved.
     * @returns A promise that is resolved when wasm is loaded.
     */
    function loadWasm(script, options) {
        options = options || {};
        const { url, init } = options;
        return new Promise(resolve => {
            self.Module = {
                onRuntimeInitialized() {
                    init && init();
                    resolve(null);
                },
                locateFile(path, prefix) {
                    return (url || prefix) + path;
                }
            };
            importScripts((url || '') + script);
        });
    }

    const instanceOfAny = (object, constructors) => constructors.some((c) => object instanceof c);

    let idbProxyableTypes;
    let cursorAdvanceMethods;
    // This is a function to prevent it throwing up in node environments.
    function getIdbProxyableTypes() {
        return (idbProxyableTypes ||
            (idbProxyableTypes = [
                IDBDatabase,
                IDBObjectStore,
                IDBIndex,
                IDBCursor,
                IDBTransaction,
            ]));
    }
    // This is a function to prevent it throwing up in node environments.
    function getCursorAdvanceMethods() {
        return (cursorAdvanceMethods ||
            (cursorAdvanceMethods = [
                IDBCursor.prototype.advance,
                IDBCursor.prototype.continue,
                IDBCursor.prototype.continuePrimaryKey,
            ]));
    }
    const cursorRequestMap = new WeakMap();
    const transactionDoneMap = new WeakMap();
    const transactionStoreNamesMap = new WeakMap();
    const transformCache = new WeakMap();
    const reverseTransformCache = new WeakMap();
    function promisifyRequest(request) {
        const promise = new Promise((resolve, reject) => {
            const unlisten = () => {
                request.removeEventListener('success', success);
                request.removeEventListener('error', error);
            };
            const success = () => {
                resolve(wrap(request.result));
                unlisten();
            };
            const error = () => {
                reject(request.error);
                unlisten();
            };
            request.addEventListener('success', success);
            request.addEventListener('error', error);
        });
        promise
            .then((value) => {
            // Since cursoring reuses the IDBRequest (*sigh*), we cache it for later retrieval
            // (see wrapFunction).
            if (value instanceof IDBCursor) {
                cursorRequestMap.set(value, request);
            }
            // Catching to avoid "Uncaught Promise exceptions"
        })
            .catch(() => { });
        // This mapping exists in reverseTransformCache but doesn't doesn't exist in transformCache. This
        // is because we create many promises from a single IDBRequest.
        reverseTransformCache.set(promise, request);
        return promise;
    }
    function cacheDonePromiseForTransaction(tx) {
        // Early bail if we've already created a done promise for this transaction.
        if (transactionDoneMap.has(tx))
            return;
        const done = new Promise((resolve, reject) => {
            const unlisten = () => {
                tx.removeEventListener('complete', complete);
                tx.removeEventListener('error', error);
                tx.removeEventListener('abort', error);
            };
            const complete = () => {
                resolve();
                unlisten();
            };
            const error = () => {
                reject(tx.error || new DOMException('AbortError', 'AbortError'));
                unlisten();
            };
            tx.addEventListener('complete', complete);
            tx.addEventListener('error', error);
            tx.addEventListener('abort', error);
        });
        // Cache it for later retrieval.
        transactionDoneMap.set(tx, done);
    }
    let idbProxyTraps = {
        get(target, prop, receiver) {
            if (target instanceof IDBTransaction) {
                // Special handling for transaction.done.
                if (prop === 'done')
                    return transactionDoneMap.get(target);
                // Polyfill for objectStoreNames because of Edge.
                if (prop === 'objectStoreNames') {
                    return target.objectStoreNames || transactionStoreNamesMap.get(target);
                }
                // Make tx.store return the only store in the transaction, or undefined if there are many.
                if (prop === 'store') {
                    return receiver.objectStoreNames[1]
                        ? undefined
                        : receiver.objectStore(receiver.objectStoreNames[0]);
                }
            }
            // Else transform whatever we get back.
            return wrap(target[prop]);
        },
        set(target, prop, value) {
            target[prop] = value;
            return true;
        },
        has(target, prop) {
            if (target instanceof IDBTransaction &&
                (prop === 'done' || prop === 'store')) {
                return true;
            }
            return prop in target;
        },
    };
    function replaceTraps(callback) {
        idbProxyTraps = callback(idbProxyTraps);
    }
    function wrapFunction(func) {
        // Due to expected object equality (which is enforced by the caching in `wrap`), we
        // only create one new func per func.
        // Edge doesn't support objectStoreNames (booo), so we polyfill it here.
        if (func === IDBDatabase.prototype.transaction &&
            !('objectStoreNames' in IDBTransaction.prototype)) {
            return function (storeNames, ...args) {
                const tx = func.call(unwrap(this), storeNames, ...args);
                transactionStoreNamesMap.set(tx, storeNames.sort ? storeNames.sort() : [storeNames]);
                return wrap(tx);
            };
        }
        // Cursor methods are special, as the behaviour is a little more different to standard IDB. In
        // IDB, you advance the cursor and wait for a new 'success' on the IDBRequest that gave you the
        // cursor. It's kinda like a promise that can resolve with many values. That doesn't make sense
        // with real promises, so each advance methods returns a new promise for the cursor object, or
        // undefined if the end of the cursor has been reached.
        if (getCursorAdvanceMethods().includes(func)) {
            return function (...args) {
                // Calling the original function with the proxy as 'this' causes ILLEGAL INVOCATION, so we use
                // the original object.
                func.apply(unwrap(this), args);
                return wrap(cursorRequestMap.get(this));
            };
        }
        return function (...args) {
            // Calling the original function with the proxy as 'this' causes ILLEGAL INVOCATION, so we use
            // the original object.
            return wrap(func.apply(unwrap(this), args));
        };
    }
    function transformCachableValue(value) {
        if (typeof value === 'function')
            return wrapFunction(value);
        // This doesn't return, it just creates a 'done' promise for the transaction,
        // which is later returned for transaction.done (see idbObjectHandler).
        if (value instanceof IDBTransaction)
            cacheDonePromiseForTransaction(value);
        if (instanceOfAny(value, getIdbProxyableTypes()))
            return new Proxy(value, idbProxyTraps);
        // Return the same value back if we're not going to transform it.
        return value;
    }
    function wrap(value) {
        // We sometimes generate multiple promises from a single IDBRequest (eg when cursoring), because
        // IDB is weird and a single IDBRequest can yield many responses, so these can't be cached.
        if (value instanceof IDBRequest)
            return promisifyRequest(value);
        // If we've already transformed this value before, reuse the transformed value.
        // This is faster, but it also provides object equality.
        if (transformCache.has(value))
            return transformCache.get(value);
        const newValue = transformCachableValue(value);
        // Not all types are transformed.
        // These may be primitive types, so they can't be WeakMap keys.
        if (newValue !== value) {
            transformCache.set(value, newValue);
            reverseTransformCache.set(newValue, value);
        }
        return newValue;
    }
    const unwrap = (value) => reverseTransformCache.get(value);

    /**
     * Open a database.
     *
     * @param name Name of the database.
     * @param version Schema version.
     * @param callbacks Additional callbacks.
     */
    function openDB(name, version, { blocked, upgrade, blocking, terminated } = {}) {
        const request = indexedDB.open(name, version);
        const openPromise = wrap(request);
        if (upgrade) {
            request.addEventListener('upgradeneeded', (event) => {
                upgrade(wrap(request.result), event.oldVersion, event.newVersion, wrap(request.transaction), event);
            });
        }
        if (blocked) {
            request.addEventListener('blocked', (event) => blocked(
            // Casting due to https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1405
            event.oldVersion, event.newVersion, event));
        }
        openPromise
            .then((db) => {
            if (terminated)
                db.addEventListener('close', () => terminated());
            if (blocking) {
                db.addEventListener('versionchange', (event) => blocking(event.oldVersion, event.newVersion, event));
            }
        })
            .catch(() => { });
        return openPromise;
    }

    const readMethods = ['get', 'getKey', 'getAll', 'getAllKeys', 'count'];
    const writeMethods = ['put', 'add', 'delete', 'clear'];
    const cachedMethods = new Map();
    function getMethod(target, prop) {
        if (!(target instanceof IDBDatabase &&
            !(prop in target) &&
            typeof prop === 'string')) {
            return;
        }
        if (cachedMethods.get(prop))
            return cachedMethods.get(prop);
        const targetFuncName = prop.replace(/FromIndex$/, '');
        const useIndex = prop !== targetFuncName;
        const isWrite = writeMethods.includes(targetFuncName);
        if (
        // Bail if the target doesn't exist on the target. Eg, getAll isn't in Edge.
        !(targetFuncName in (useIndex ? IDBIndex : IDBObjectStore).prototype) ||
            !(isWrite || readMethods.includes(targetFuncName))) {
            return;
        }
        const method = async function (storeName, ...args) {
            // isWrite ? 'readwrite' : undefined gzipps better, but fails in Edge :(
            const tx = this.transaction(storeName, isWrite ? 'readwrite' : 'readonly');
            let target = tx.store;
            if (useIndex)
                target = target.index(args.shift());
            // Must reject if op rejects.
            // If it's a write operation, must reject if tx.done rejects.
            // Must reject with op rejection first.
            // Must resolve with op value.
            // Must handle both promises (no unhandled rejections)
            return (await Promise.all([
                target[targetFuncName](...args),
                isWrite && tx.done,
            ]))[0];
        };
        cachedMethods.set(prop, method);
        return method;
    }
    replaceTraps((oldTraps) => ({
        ...oldTraps,
        get: (target, prop, receiver) => getMethod(target, prop) || oldTraps.get(target, prop, receiver),
        has: (target, prop) => !!getMethod(target, prop) || oldTraps.has(target, prop),
    }));

    var luna_pinyin$1 = [
    	{
    		name: "luna_pinyin.prism.bin",
    		md5: "1a14610ed34296bc8467382db466f80f"
    	},
    	{
    		name: "luna_pinyin.reverse.bin",
    		md5: "d16701cc9cc16ab74f3b60b336409bf1"
    	},
    	{
    		name: "luna_pinyin.schema.yaml",
    		md5: "9cd301a052bf114471468e21d6206453"
    	},
    	{
    		name: "luna_pinyin.table.bin",
    		md5: "153ea95bab6e4ee20abff0f5dfec6ead"
    	}
    ];
    var tiger$1 = [
    	{
    		name: "tiger.prism.bin",
    		md5: "46b1126c3a0fe0ad6e613fa942da702b"
    	},
    	"PY_c",
    	"easy_english",
    	{
    		name: "tiger.reverse.bin",
    		md5: "53a4eb4046558f3961dd97787911005a"
    	},
    	{
    		name: "tiger.schema.yaml",
    		md5: "0bfc9faf4d396b425a9ffa5ad4368648"
    	},
    	{
    		name: "tiger.table.bin",
    		md5: "a75199d8c9828eee4fd3af5af58cfd11"
    	}
    ];
    var tigress$1 = [
    	{
    		name: "tigress.prism.bin",
    		md5: "087ea8b6587a01a7fdfee8a68b27da5f"
    	},
    	"PY_c",
    	"easy_english",
    	{
    		name: "tigress.reverse.bin",
    		md5: "798ca1c124e14bee7a30302f50af3896"
    	},
    	{
    		name: "tigress.schema.yaml",
    		md5: "831e6a8b29fdcf9305cd87cd2444f406"
    	},
    	{
    		name: "tigress.table.bin",
    		md5: "458a129a3238db27d02aee83d1502b0a"
    	}
    ];
    var easy_english$1 = [
    	{
    		name: "easy_english.prism.bin",
    		md5: "92ca734d043324eecc1a07e3b20681bf"
    	},
    	{
    		name: "easy_english.reverse.bin",
    		md5: "f93f7763d8a55651ba6552a230d4758b"
    	},
    	{
    		name: "easy_english.schema.yaml",
    		md5: "b2f7fc5ec0e141f4376123f3405b0c6a"
    	},
    	{
    		name: "easy_english.table.bin",
    		md5: "1428d684d15d056b30aa771e386ad614"
    	}
    ];
    var PY_c$1 = [
    	{
    		name: "PY_c.prism.bin",
    		md5: "16f66855857527ce3e94d6184719a17f"
    	},
    	"stroke",
    	{
    		name: "PY_c.reverse.bin",
    		md5: "e1064a2450749be4541e403d0e798d27"
    	},
    	{
    		name: "PY_c.schema.yaml",
    		md5: "8604b2364cee5b5b9c5cd289e0dd9626"
    	},
    	{
    		name: "PY_c.table.bin",
    		md5: "ed070ee3929791e58436b5a6ec5d3289"
    	}
    ];
    var stroke$1 = [
    	{
    		name: "stroke.prism.bin",
    		md5: "439f49c29f334fa9a4d2a695b69caefd"
    	},
    	"luna_pinyin",
    	{
    		name: "stroke.reverse.bin",
    		md5: "2a48d464df9af2b4d7357a0b7d14090f"
    	},
    	{
    		name: "stroke.schema.yaml",
    		md5: "44e4e9b9b7560c88374b6227816567d4"
    	},
    	{
    		name: "stroke.table.bin",
    		md5: "338d1760e7d1f9e964705436555d7681"
    	}
    ];
    var schemaFiles = {
    	luna_pinyin: luna_pinyin$1,
    	tiger: tiger$1,
    	tigress: tigress$1,
    	easy_english: easy_english$1,
    	PY_c: PY_c$1,
    	stroke: stroke$1
    };

    var luna_pinyin = "luna-pinyin";
    var tiger = "bczhc/rime-tiger-code";
    var tigress = "bczhc/rime-tiger-code";
    var easy_english = "bczhc/rime-tiger-code";
    var PY_c = "bczhc/rime-tiger-code";
    var stroke = "stroke";
    var schemaTarget = {
    	luna_pinyin: luna_pinyin,
    	tiger: tiger,
    	tigress: tigress,
    	easy_english: easy_english,
    	PY_c: PY_c,
    	stroke: stroke
    };

    const HASH = 'hash';
    const CONTENT = 'content';
    const prefix = ('' + 'ime/');
    const dbPromise = openDB('ime', 1, {
        upgrade(db) {
            db.createObjectStore(HASH);
            db.createObjectStore(CONTENT);
        }
    });
    async function setIME(schemaId) {
        const fetched = [];
        function getFiles(key) {
            if (fetched.includes(key)) {
                return [];
            }
            fetched.push(key);
            const files = [];
            for (const item of schemaFiles[key]) {
                if (typeof item === 'string') { // root schema_id
                    files.push(...getFiles(item));
                }
                else {
                    files.push({ ...item, target: schemaTarget[key] });
                }
            }
            return files;
        }
        const files = getFiles(schemaId);
        const db = await dbPromise.catch(() => undefined); // not available in Firefox Private Browsing
        await Promise.all(files.map(async ({ name, target, md5 }) => {
            const path = `build/${name}`;
            try {
                Module.FS.lookupPath(path);
            }
            catch (e) { // not exists
                const storedHash = await db?.get(HASH, name);
                let ab;
                if (storedHash === md5) {
                    ab = await db.get(CONTENT, name);
                }
                else {
                    const response = await fetch(`${prefix}${target}/${name}`);
                    if (!response.ok) {
                        throw new Error(`Fail to download ${name}`);
                    }
                    ab = await response.arrayBuffer();
                    await db?.put(CONTENT, ab, name);
                    await db?.put(HASH, md5, name);
                }
                Module.FS.writeFile(path, new Uint8Array(ab));
            }
        }));
        Module.ccall('set_ime', 'null', ['string'], [schemaId]);
    }
    const readyPromise = loadWasm('rime.js', {
        url: '',
        init() {
            Module.ccall('init', 'null', [], []);
            Module.FS.mkdir('build');
        }
    });
    expose({
        setIME,
        setOption(option, value) {
            return Module.ccall('set_option', 'null', ['string', 'number'], [option, value]);
        },
        process(input) {
            return Module.ccall('process', 'string', ['string'], [input]);
        }
    }, readyPromise);

})();
